/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package LeetCode

import kotlin.test.Test
import kotlin.test.assertNotNull

final class AppTest {
    @Test fun appHasQuestion() {
        // given
        val app = App()
        // then
        assertNotNull(app.question)
    }
}
