/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package LeetCode

class App {
    val question = ReverseWordsInAString()
}

fun main() {
    println(App().question.solution("the sky is blu"))
}
